[package]
name = "rust-learning"
version = "0.1.0"
authors = ["b3hr4d <behradmusiclove@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
